[package]
name = "passphrase_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
rand = "0.8.5"
config = "0.12"
serde = {version = "1.0", features = ["derive"]}